---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-superfs
spec:
  selector:
    app: eureka-service-superfs
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-superfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service-superfs
  template:
    metadata:
      labels:
        app: eureka-service-superfs
    spec:
      containers:
        - name: eureka-service-superfs
          image: elu107/eureka-service-superfs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
